[package]
name = "aoc10"
version = "0.1.0"
authors = ["Till Rohrmann <trohrmann@apache.org>"]
edition = "2018"

[dependencies]
aoc_common = { path = "../aoc_common" }
regex = "1.1.2"
lazy_static = "1.3.0"
