[package]
name = "aoc7"
version = "0.1.0"
authors = ["Till Rohrmann <trohrmann@apache.org>"]
edition = "2018"

[dependencies]
aoc_common = { path = "../aoc_common", version = "0.1.0" }
regex = "1.1.0"
lazy_static = "1.2.0"