[package]
name = "aoc_2021_13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_common = { path = "../aoc_common" }
regex = "1.5"
lazy_static = "1.4.0"