[package]
name = "aoc_2019_10"
version = "0.1.0"
authors = ["Till Rohrmann <trohrmann@apache.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_common = { path = "../aoc_common" }